### ISSUE TITLE
.js files always have a single line, is the code up to date?

### ISSUE THREAD

**Issue by ghost** [jhoenicke/mempool#45]
The updatedata.sh script keeps updating all .js files but instead of appending data points to it, it always keeps a single value, replacing them every minute when the crontab runs 
(the Mysql table is increased one record per minute though).
Is this behaviour expected?

**Comment by ghost** [comment]
It seems this commit https://github.com/jhoenicke/mempool/commit/ceaff66bbb894225bb82be35557a141dbcd2f1df caused the issue, before that, every minute a new data point is added to 2h.js and others

**Comment by jhoenicke** [comment]
The problem is that the script now always removes the first data point and adds one new. So there is currently a bootstrapping problem, if initially you don't have enough data points.  If you remove the temporary directory `$DESTDIR` (but keep mempool.log) and run the script again, it should recreate all js files with the right number of data points. Provided there are enough data points in mempool.log.
