### ISSUE TITLE
Scale of BSV fees should use different values

### ISSUE THREAD

**Issue by torusJKL** [jhoenicke/mempool#47]
The average fees on BSV are below 0.5 sat/byte.
Hence the used scale of 0-1 sat/byte and going up to 500+ sat does not reflect the situation on BSV.

Instead the scale should show ranges with fraction of satoshi levels so that it is possible to see e.g. 0.25 sat/byte payments.

**Comment by jhoenicke** [comment]
It's not too difficult to change the ranges, but it would require me to update the existing database, which is always a bit of a pain.  

Unfortunately, my BSV server is on its limit.  The disk is almost full, and the bitcoin client uses 2 GB swap because of too low memory.  I would need a larger server to continue to run it, which I don't have plans for at the moment.  So it doesn't make sense to update the database, if the server will stop running in a few weeks.

**Comment by mrz1836** [comment]
Thanks for all your hard work @jhoenicke - loved using your site to reference mempool data. Sad to see BSV go but if you are able to support it again in the future that would be amazing!

**Comment by jhoenicke** [comment]
I now have the BSV server running again, this time in pruned mode.  I updated the fee scales.

However, I didn't update historic data, so they will now show the fee with the wrong values. Also there is a huge gap between February and May where no data  was collected.

**Comment by torusJKL** [comment]
Thanks for bringing it back and updating the fee scale!
