### ISSUE TITLE
Fee level cut offs inclusive?

### ISSUE THREAD

**Issue by dabura667** [jhoenicke/mempool#5]
0-5 and 5-10 leaves the question: If the transaction is exactly 5 satoshis per byte, which color is it?

Perhaps make a note on the site: "for each level lower bound inclusive upper bound exclusive" etc.

If there's some way to make this obvious in the fee level legend it would be best, but I'm not a UI guy.

**Comment by jhoenicke** [comment]
FYI, since end of April the lower bound is inclusive, the upper bound is exclusive (before it was random due to rounding errors).  It only affects few transactions that aim for exactly this limit and have a signature of maximum size (signature size is variable and cannot be known before signing).

I have to think about how to make it this clear.

**Comment by dabura667** [comment]
For now, a small asterisk next to the legend and a footnote explaining should be sufficient.
