### ISSUE TITLE
Invalid transactions in the mempool?

### ISSUE THREAD

**Issue by Transisto** [jhoenicke/mempool#51]
![image](https://user-images.githubusercontent.com/388716/83905784-466c6880-a730-11ea-9573-d627e4fcbf19.png)

![image](https://user-images.githubusercontent.com/388716/83905895-803d6f00-a730-11ea-9c23-374334fb729e.png)

**Comment by Transisto** [comment]
![image](https://user-images.githubusercontent.com/388716/83906152-0bb70000-a731-11ea-94eb-bf7e103a7d2d.png)

**Comment by jhoenicke** [comment]
These are transactions that were lost by nodes with default mempool settings, probably because the mempool reached the size limit (you can see that happened on the node with default mempool settings). They were never replayed (in contrast to many other evicted transactions), but they are still valid.  In particular, I could replay them, since my node still has them. However, I'm not sure, if this is a good idea to replay them.

**Comment by jhoenicke** [comment]
They were either replayed or double-spend now, so they are no longer waiting.

**Comment by Transisto** [comment]
Good to know thanks!

I'm surprised there isn't anyone with more lax mempool rule replaying those. I'd have expected a miner would have kept them for some extra fees.
