### ISSUE TITLE
Are there transactions below 1sat/bytes?

### ISSUE THREAD

**Issue by Transisto** [jhoenicke/mempool#74]
![image](https://user-images.githubusercontent.com/388716/202087988-e3370212-78a6-4d65-adc9-f01826e034b4.png)

205-145 = 50mb, 

There's 50mb that's shown as below the relay fee of 1/sat bytes.  How is this possible ? Is this a bug?

**Comment by jhoenicke** [comment]
It's a feature :) The first node is running with very low minimum relay fee so it will accept and relay transactions with less than 1 sat/byte.  In my experience, there is no miner willing to accept and mine these transactions.  So the transactions will stay in the pool until they are either double-spent or they expire.  Since I also chose a very long expiry period they accumulate over time.

**Comment by Transisto** [comment]
Very interesting, thanks for your answer.

I find it surprising that you manage to get them relayed meaning miners also do but prefer to forgo 0.5sat/bytes profits and mine half empty blocks.
